import { KeyboardEvent, useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { apiFetch, ApiError } from "../lib/api";
import { useObjectUrl } from "../lib/hooks";
import { errorText, t, warningText } from "../i18n/ja";

type Glyph = { codepoint: number; char: string; status: "missing" | "auto" | "accepted" | "rejected"; advance: number | null; warnings: string[]; svg_url?: string; updated_at?: string };
const section = (cp: number) => cp <= 0x7e ? "英数" : cp >= 0x3041 && cp <= 0x3096 ? "ひらがな" : cp >= 0x30a1 && cp <= 0x30fc ? "カタカナ" : "記号";
const statusLabel: Record<Glyph["status"], string> = { missing: "未取込", auto: "未確認", accepted: "採用", rejected: "却下" };
function GlyphPreview({ projectId, glyph }: { projectId: string; glyph: Glyph }) {
  const [blob, setBlob] = useState<Blob>();
  const url = useObjectUrl(blob);
  useEffect(() => { if (glyph.svg_url) void apiFetch<Blob>(`/projects/${projectId}/glyphs/${glyph.codepoint}.svg`, { projectId, raw: true }).then(setBlob).catch(() => undefined); }, [glyph.codepoint, glyph.svg_url, projectId]);
  return url ? <img src={url} alt="" /> : <span className="missing-char">{glyph.char}</span>;
}
export default function Review() { const { projectId = "" } = useParams(); const client = useQueryClient(); const [filter, setFilter] = useState("all"); const [search, setSearch] = useState(""); const [selected, setSelected] = useState<number[]>([]);
  const query = useQuery({ queryKey: ["glyphs", projectId], queryFn: () => apiFetch<{ glyphs: Glyph[] }>(`/projects/${projectId}/glyphs?limit=300`, { projectId }) });
  const review = useMutation({ mutationFn: (payload: { accept: number[]; reject: number[] }) => apiFetch(`/projects/${projectId}/glyphs:review`, { method: "POST", body: payload, projectId }), onMutate: async (payload) => { await client.cancelQueries({ queryKey: ["glyphs", projectId] }); const previous = query.data; client.setQueryData<{ glyphs: Glyph[] }>(["glyphs", projectId], (old) => old && { glyphs: old.glyphs.map((glyph) => payload.accept.includes(glyph.codepoint) ? { ...glyph, status: "accepted" } : payload.reject.includes(glyph.codepoint) ? { ...glyph, status: "rejected" } : glyph) }); return { previous }; }, onError: (_error, _payload, context) => client.setQueryData(["glyphs", projectId], context?.previous), onSettled: () => { void client.invalidateQueries({ queryKey: ["summary", projectId] }); } });
  const glyphs = useMemo(() => (query.data?.glyphs ?? []).filter((glyph) => (filter === "all" || (filter === "warning" ? glyph.warnings.length > 0 : glyph.status === filter)) && (!search || glyph.char.includes(search) || `U+${glyph.codepoint.toString(16).toUpperCase()}`.includes(search.toUpperCase()))), [filter, search, query.data]);
  function act(codepoints: number[], action: "accept" | "reject") { if (codepoints.length) review.mutate(action === "accept" ? { accept: codepoints, reject: [] } : { accept: [], reject: codepoints }); setSelected([]); }
  function keyboard(event: KeyboardEvent<HTMLButtonElement>, index: number, cp: number) { const target = event.key === "a" ? "accept" : event.key === "r" ? "reject" : undefined; if (target) { event.preventDefault(); act([cp], target); } else if (["ArrowRight", "ArrowDown"].includes(event.key)) document.querySelectorAll<HTMLButtonElement>(".glyph-cell")[index + 1]?.focus(); else if (["ArrowLeft", "ArrowUp"].includes(event.key)) document.querySelectorAll<HTMLButtonElement>(".glyph-cell")[Math.max(0, index - 1)]?.focus(); else if (event.key === "Escape") setSelected([]); }
  return <section><div className="page-heading"><div><p className="eyebrow">03 / 04</p><h1>{t("review")}</h1><p>文字を確認して、フォントに含める文字を選びます。</p></div><Link className="button" to={`/p/${projectId}/build`}>ビルドへ</Link></div><div className="review-toolbar"><input placeholder="文字・U+コードを検索" value={search} onChange={(event) => setSearch(event.target.value)} />{[["all", "すべて"], ["auto", "未確認"], ["accepted", "採用"], ["rejected", "却下"], ["missing", "未取込"], ["warning", "警告あり"]].map(([value, label]) => <button className={filter === value ? "active" : ""} key={value} onClick={() => setFilter(value)}>{label}</button>)}<button onClick={() => { if (window.confirm(`AUTOをすべて採用しますか？`)) act((query.data?.glyphs ?? []).filter((glyph) => glyph.status === "auto").map((glyph) => glyph.codepoint), "accept"); }}>AUTOをすべて採用</button></div>{query.error && <p className="notice error">{errorText(query.error instanceof ApiError ? query.error.code : "E_INTERNAL")}</p>}<div className="review-grid">{["英数", "ひらがな", "カタカナ", "記号"].map((name) => <div className="glyph-section" key={name}><h2>{name}</h2><div className="grid">{glyphs.filter((glyph) => section(glyph.codepoint) === name).map((glyph, index) => <button key={glyph.codepoint} className={`glyph-cell status-${glyph.status} ${selected.includes(glyph.codepoint) ? "selected" : ""}`} aria-label={`${glyph.char} ${statusLabel[glyph.status]}`} onKeyDown={(event) => keyboard(event, index, glyph.codepoint)} onClick={() => setSelected((old) => old.includes(glyph.codepoint) ? old.filter((cp) => cp !== glyph.codepoint) : [...old, glyph.codepoint])}>{glyph.status === "missing" || !glyph.svg_url ? <span className="missing-char">{glyph.char}</span> : <GlyphPreview projectId={projectId} glyph={glyph} />}<small>{glyph.char} · {statusLabel[glyph.status]}</small>{glyph.warnings.length > 0 && <i title={glyph.warnings.map(warningText).join("、")}>!</i>}</button>)}</div></div>)}</div>{selected.length > 0 && <div className="selection-bar"><span>{selected.length}字を選択中</span><button className="button" onClick={() => act(selected, "accept")}>採用</button><button className="button secondary" onClick={() => act(selected, "reject")}>却下</button></div>}</section>;
}
