import hashlib
from concurrent.futures import ThreadPoolExecutor
from uuid import uuid4

import pytest
from service_test_support import auth

from glyphlab_service.api.template import artifact_key
from glyphlab_service.db.models import Artifact, Glyph


def test_build_empty_and_singleflight(client, app, project):
    path = "/api/projects/" + project["project_id"] + "/builds"
    assert (
        client.post(path, headers=auth(project), json={}).json()["error"]["detail"]["reason"]
        == "nothing_to_build"
    )
    with app.state.session_factory.begin() as s:
        s.get(Glyph, (project["project_id"], 65)).status = "auto"
    with ThreadPoolExecutor(max_workers=2) as pool:
        responses = list(
            pool.map(lambda _: client.post(path, headers=auth(project), json={}), range(2))
        )
    assert sorted(r.status_code for r in responses) == [202, 409]
    job_id = next(r.json()["job_id"] for r in responses if r.status_code == 202)
    assert (
        next(r.json()["error"]["detail"]["job_id"] for r in responses if r.status_code == 409)
        == job_id
    )


@pytest.mark.parametrize(
    "kind,mime",
    [
        ("ttf", "font/ttf"),
        ("woff2", "font/woff2"),
        ("proof_html", "text/html"),
        ("qa_json", "application/json"),
        ("template_pdf", None),
        ("template_sidecar", None),
    ],
)
def test_download_headers(client, app, project, kind, mime):
    data = b"example generated bytes"
    with app.state.session_factory.begin() as s:
        artifact = Artifact(
            project_id=project["project_id"],
            kind=kind,
            storage_key=uuid4().hex,
            bytes=len(data),
            sha256=hashlib.sha256(data).hexdigest(),
        )
        s.add(artifact)
        s.flush()
        app.state.store.put(artifact_key(artifact), data, mime or "application/json")
    path = "/api/projects/" + project["project_id"] + "/artifacts/" + artifact.id
    assert client.get(path).status_code == 404
    response = client.get(path, headers=auth(project))
    if mime is None:
        assert response.status_code == 404
        return
    assert response.content == data and response.headers["Content-Type"].startswith(mime)
    assert response.headers["Cache-Control"] == "private, no-store"
    assert response.headers["X-Content-Type-Options"] == "nosniff"
    if kind == "proof_html":
        assert response.headers["Content-Security-Policy"] == "sandbox"
    else:
        assert response.headers["Content-Disposition"].startswith("attachment;")
